---
# Deploy the app, note: don't do these tasks with become sudo
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes

    - name: Install packages
      become: true
      apt:
        name: apt-transport-https
        state: present
        update_cache: true

    - name: Install packages
      become: true
      apt:
        name: lsb-release
        state: present
        update_cache: true

    - name: Install packages
      become: true
      apt:
        name: git
        state: present
        update_cache: true
      
    - name: Install packages
      become: true
      apt:
        name: curl
        state: present
        update_cache: true

    - name: Install packages
      become: true
      apt:
        name: ca-certificates
        state: present
        update_cache: true

    - name: Deb nodejs
      become: true
      shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

    - name: Install nodejs
      become: true
      apt:
        name: nodejs
        state: present
        update_cache: true

    - name: Just get information about the repository whether or not it has already been cloned locally
      become: true
      git:
        repo: 'https://github.com/pantsel/konga'
        dest: /usr/conf/kong/konga

    - name: Copy file with owner and permissions
      become: true
      copy:
        src: /usr/conf/kong/.env
        dest: /usr/conf/kong/konga/.env

        